export enum Color {
  Black = 'black',
  Red = 'red',
  Green = 'green',
  Yellow = 'yellow',
  Blue = 'blue',
  Magenta = 'magenta',
  Cyan = 'cyan',
  White = 'white',
  Gray = 'Gray',
  Grey = 'Grey',
  BrightBlack = 'blackBright',
  BrightRed = 'redBright',
  BrightGreen = 'greenBright',
  BrightYellow =  'yellowBright',
  BrightBlue = 'blueBright',
  BrightMagenta = 'magentaBright',
  BrightCyan = 'cyanBright',
  BrightWhite = 'whiteBright',
};
